# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  my-executor:
    docker:
      - image: debian:stretch

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run: 'apt-get update && apt-get install -y gcc g++'
      - run: 'apt-get update && sudo apt-get install -y cmake'
      - run: 'mkdir build'
      - run: 'cd build && cmake -H. -Bbuild ../src'
      - run: 'cmake --build build'
      - run: './build/bin/testPoint'